---
title: "Biodiversity"
author: "Georgie Stammer"
date: '2022-04-18'
output: html_document
---

```{r setup message = FALSE, include = FALSE}
library(tidyverse)
library(socviz)
library(sf)
library(rgdal)
library(broom)
library(rnaturalearth)
library(rnaturalearthdata)
library(maps)
```

```{r load-data, message = FALSE, warning = FALSE}
CRgdb <- st_read(dsn = "data/WDPA_Apr2022_Public/WDPA_Apr2022_Public.gdb",
                 layer = "WDPA_poly_Apr2022")

borders <- readOGR(dsn = "data/gadm40_CRI_shp/", layer = "gadm40_CRI_0")
bordersPAN <- readOGR(dsn = "data/gadm40_PAN_shp/", layer = "gadm40_PAN_0")
bordersNIC <- readOGR(dsn = "data/gadm40_NIC_shp/", layer = "gadm40_NIC_0")
```

```{r clean-data}
tidyCR <- tibble(CRgdb) %>%
  filter(ISO3 == "CRI")

cleanCR <- tidyCR %>%
  filter(STATUS == "Designated") %>%
  filter(MARINE < 1) %>%
  select(WDPAID, NAME, DESIG_ENG, DESIG_TYPE, MARINE, GIS_AREA,
         STATUS_YR, GOV_TYPE, OWN_TYPE, SHAPE)

cleanCRmarine <- tidyCR %>%
  filter(STATUS == "Designated") %>%
  filter(MARINE > 0) %>%
  select(WDPAID, NAME, DESIG_ENG, DESIG_TYPE, MARINE, GIS_AREA,
         STATUS_YR, GOV_TYPE, OWN_TYPE, SHAPE)
```

```{r quick-analysis}
cleanCR %>%
  count(GOV_TYPE)

cleanCR %>%
  count(OWN_TYPE)

cleanCR %>%
  count(DESIG_ENG)

cleanCR %>%
  count(MARINE)
```

```{r map-theme}
theme_crmap <- function(base_size=9, base_family="") {
    require(grid)
    theme_bw(base_size=base_size, base_family=base_family) %+replace%
        theme(axis.line=element_blank(),
              axis.text=element_blank(),
              axis.ticks=element_blank(),
              axis.title=element_blank(),
              panel.background=element_rect(fill = "black"),
              panel.border=element_blank(),
              panel.grid=element_blank(),
              panel.spacing=unit(0, "lines"),
              plot.background=element_rect(fill = "black"),
              legend.position = "bottom", 
              legend.direction = "horizontal",
              legend.background = element_rect(fill = "black"),
              legend.text = element_text(color = "white")
        )
}
```


```{r maps}
borders_tidy <- tidy(borders)
borders_tidyPAN <- tidy(bordersPAN)
borders_tidyNIC <- tidy(bordersNIC)


ggplot() +
  geom_sf(data = cleanCR, aes(geometry = SHAPE), color = "black",
          fill = "#00C1AA", size = 0.1) +
  geom_sf(data = cleanCRmarine, aes(geometry = SHAPE), color = "black",
          fill = "#00B4EF", size = 0.1) +
  geom_polygon(data = borders_tidy, aes(x = long, y = lat, group = group),
               fill="transparent", color="white", size = 0.2) +
  geom_polygon(data = borders_tidyPAN, aes(x = long, y = lat, group = group),
               fill="transparent", color="white", size = 0.2) +
  geom_polygon(data = borders_tidyNIC, aes(x = long, y = lat, group = group),
               fill="transparent", color="white", size = 0.2) +
  theme_crmap() +
  xlim(-88, -81) +
  ylim(7, 16)

ggplot() +
  geom_sf(data = cleanCR, aes(fill = STATUS_YR, geometry = SHAPE),
          color = "black", size = 0.1) +
  geom_sf(data = cleanCRmarine, aes(fill = STATUS_YR, geometry = SHAPE),
          color = "black", size = 0.1) +
  geom_polygon(data = borders_tidy, aes(x = long, y = lat, group = group),
               fill="transparent", color="white", size = 0.2) +
  theme_crmap() +
  xlim(-87, -81) +
  ylim(7, 12)

ggplot() +
  geom_sf(data = cleanCR, aes(fill = DESIG_ENG, geometry = SHAPE),
          color = "black", size = 0.1) +
  geom_sf(data = cleanCRmarine, aes(fill = DESIG_ENG, geometry = SHAPE),
          color = "black", size = 0.1) +
  geom_polygon(data = borders_tidy, aes(x = long, y = lat, group = group),
               fill="transparent", color="white", size = 0.2) +
  theme_crmap() +
  xlim(-87, -82) +
  ylim(8, 12)
```





